### ISSUE TITLE
What do you guys want later in the 1.2 update?

### ISSUE THREAD

**Issue by audiotore341** [audiotore341/CodinOS#1]

**Comment by Yaumama** [comment]
Easter eggs

**Comment by kenan238** [comment]
actual bootable os in C and Assembly

**Comment by audiotore341** [comment]
> actual bootable os in C and Assembly

Sorry, I am not advanced enough for that.

**Comment by audiotore341** [comment]
> Easter eggs

You got it!

**Comment by audiotore341** [comment]
Releasing update now.
